### ISSUE TITLE
[Bug] 프로필뷰의 meal 관련 버그 수정

### ISSUE THREAD

**Issue by eunbkang** [Bnomad-space/IAteIt#113]
### Bug 내용

- 프로필뷰의 개별 meal detailView에서 수정(캡션, 장소, plate 추가/삭제, 댓글) 시 바로 반영 안되어 보이는 문제
- 프로필뷰에서 meal 삭제 시 바로 반영 안되어 보이는 문제
- 프로필뷰의 Meal DetailView에서 가끔(?) meal 더미데이터 보이는 문제

**Comment by sunshiningsoo** [comment]
related #141
