### ISSUE TITLE
[Enhancement] Meal 설정에서 바꾸면 바로 반영 안되는 문제 휙스~

### ISSUE THREAD

**Issue by sunshiningsoo** [Bnomad-space/IAteIt#139]
### 작업할 내용

- 설정에서 Meal 관련 제목, 장소 바꾸면 바로 반영 안되는 문제 휙스(FIX~) 합니다~

### Related
- #113

**Comment by eunbkang** [comment]
휙스ㅋㅋㅋ 좋습니다
