### ISSUE TITLE
[Fix] Meal 생성 시 Plate 없는 경우 대응

### ISSUE THREAD

**Issue by eunbkang** [Bnomad-space/IAteIt#145]
### 문제 상황
- Meal 생성 시 Firestore database에 일단 빈 게시물을 만들고 자동 생성된 DocumentId를 가져와서 plate 등록 중
- 유저가 게시물 생성하다가 plate까지 완전히 등록 전 에러가 난 경우와 같은 상황에서 plate가 비어있는 Meal이 생성됨
- 모든 유저에게서 피드가 제대로 보이지 않는 문제

**Comment by sunshiningsoo** [comment]
나이스!!

**Comment by sunshiningsoo** [comment]
#146 에서 작업했습니닷

**Comment by sunshiningsoo** [comment]
close #146
