### ISSUE TITLE
[Feat] CameraView UI 구현

### ISSUE THREAD

**Issue by Willowwryu** [Bnomad-space/IAteIt#2]
### 작업할 내용

CameraView Ui
- 셔터 버튼
- 전면후면 카메라 변경 버튼
- 플래시 버튼의 ui를 구현 합니다.

### 스크린샷 혹은 gif

<img widht="300" src="https://user-images.githubusercontent.com/103012086/220826858-e63f3019-fdb1-4b87-90dc-37a37804ec67.png">

### TODO

- [x] 셔터버튼
- [x] 플래시버튼
- [x] 전면후면 카메라 변경 버튼

**Comment by hardworking-nomad** [comment]
음식 사진만 대상이라면 전면 카메라 전환보다 후면 강제 모드로만 동작하는 것도 좋을 것 같습니다

**Comment by Willowwryu** [comment]
> 음식 사진만 대상이라면 전면 카메라 전환보다 후면 강제 모드로만 동작하는 것도 좋을 것 같습니다

직전 회의 때 나왔던 주제인데 전면 카메라를 쓸 일이 있을 수도 있다는 의견이 있어서 일단 넣었습니다. 다음 회의 때 다시 한번 이야기 해보겠습니다!
